import streamlit as st
import google.generativeai as genai

# ==============================================================================
# SAYFA AYARLARI & TASARIM
# ==============================================================================
st.set_page_config(page_title="Matematik Ders Rehberi", page_icon="🎓", layout="centered")

footer_css = """
<style>
.kucuk-logo {
    position: fixed;
    bottom: 15px;
    left: 20px;
    font-size: 14px;
    font-weight: 800;
    color: #6c757d; 
    z-index: 9999;
    font-family: 'Arial', sans-serif;
    letter-spacing: 2px;
    user-select: none; 
}
</style>
<div class="kucuk-logo">ZY</div>
"""
st.markdown(footer_css, unsafe_allow_html=True)

# ==============================================================================
# DEV VERİ TABANI (TÜM DERSLER)
# ==============================================================================
dersler_db = {
    # ---------------- ZORUNLU DERSLER ----------------
    "MAT1103": {"ad": "Lineer Cebir I", "sinif": 1, "yariyil": 1, "kategori": "Cebir", "tur": "ZORUNLU", "icerik": "Bu ders; lineer denklem sistemlerinin çözümü, matris operasyonları, matrislerin cebirsel özellikleri, eşelon biçim, kofaktör açılımı ve elemanter matrisler yardımıyla matris tersi bulma tekniklerini kapsar. Özel ve parçalanmış matris yapıları ile determinant uygulamalarından başlayarak; karakteristik polinom, özdeğer (eigenvalue) analizleri, vektör kavramı ve reel vektör uzayı gibi soyut matematiksel yapıları teorik ve uygulamalı boyutta ele alır.", "meslekler": ["Yapay Zeka ve Makine Öğrenmesi Mühendisi", "3B Grafik & Oyun Motoru Yazılımcısı", "Veri Bilimci (Boyut İndirgeme Uzmanı)"]},
    "MAT1105": {"ad": "Soyut Matematik I", "sinif": 1, "yariyil": 1, "kategori": "Soyut Matematik", "tur": "ZORUNLU", "icerik": "Bu ders; önermeler mantığı, niceleyiciler ile doğrudan ispat, çelişkiyle ispat ve matematiksel tümevarım gibi temel ispat tekniklerini kapsar. Kümeler teorisi, küme operasyonları, kartezyen çarpım, bağıntı çeşitleri (denklik ve sıralama bağıntıları) ile fonksiyon kavramını (birebirlik, örtenlik ve bileşke) aksiyomatik boyutta ele alır.", "meslekler": ["Formel Doğrulama Mühendisi", "Veritabanı Mimarı", "Yazılım Mantık ve Test Uzmanı"]},
    "MAT1107": {"ad": "Analitik Geometri I", "sinif": 1, "yariyil": 1, "kategori": "Geometri", "tur": "ZORUNLU", "icerik": "Bu ders; 2 ve 3 boyutlu uzayda vektörlerin geometrik temsilini, doğru ve düzlem denklemlerini ile dik, kutupsal ve küresel koordinat sistemlerindeki dönüşümleri kapsar. Konik kesitlerini ve ikinci dereceden eğrilerin matrisel yöntemlerle standart biçimlere indirgenmesini analitik olarak inceler.", "meslekler": ["Otonom Sistemler ve Navigasyon Mühendisi", "Bilgisayar Görüsü (Computer Vision) Uzmanı", "Coğrafi Bilgi Sistemleri (CBS/GIS) Yazılımcısı"]},
    "MAT1109": {"ad": "Analiz I", "sinif": 1, "yariyil": 1, "kategori": "Analiz", "tur": "ZORUNLU", "icerik": "Bu ders; reel sayılar sisteminin aksiyomatik yapısını, dizileri, yakınsaklığı, limitin epsilon-delta tanımını ve fonksiyonlarda süreklilik kavramını kapsar. Türev tanımı, türev alma kuralları, Rolle ve Ortalama Değer Teoremleri ile L'Hopital kuralı gibi türevin temel araçlarını teorik ve uygulamalı boyutta ele alır.", "meslekler": ["Algoritma ve Optimizasyon Uzmanı", "Fizik Motoru Yazılımcısı", "Finansal Modelleme Analisti"]},
    "MAT1104": {"ad": "Lineer Cebir II", "sinif": 1, "yariyil": 2, "kategori": "Cebir", "tur": "ZORUNLU", "icerik": "Bu ders; soyut vektör uzayları, alt uzaylar, lineer bağımsızlık, taban (baz), boyut ve lineer dönüşümlerin matris temsilini kapsar. İç çarpım uzayları, Gram-Schmidt dikleştirme yöntemi, özdeğer-özvektör analizi, köşegenleştirme (diyagonalleştirme), Jordan kanonik formu ve kuadratik formları teorik ve uygulamalı boyutta ele alır.", "meslekler": ["Kuantum Yazılım Mühendisi", "Yapay Zeka Araştırmacısı (Boyut İndirgeme Uzmanı)", "Robotik Kinematik Mühendisi"]},
    "MAT1106": {"ad": "Soyut Matematik II", "sinif": 1, "yariyil": 2, "kategori": "Soyut Matematik", "tur": "ZORUNLU", "icerik": "Bu ders; kardinalite (kümelerin gücü), sonsuz kümeler, sayılabilirlik kavramı ve Cantor hipotezi gibi ileri düzey küme teorisi konularını kapsar. Bölünebilme teorisi, modüler aritmetik ve Zn yapıları üzerinden cebirsel sistemlere geçiş yaparak yarı grup, grup, halka ve cisim gibi yapay/soyut cebirsel sistemlerin temel özelliklerini inceler.", "meslekler": ["Kriptolog ve Siber Güvenlik Araştırmacısı", "Blokzincir Protokol Mühendisi", "Kodlama Teorisi Uzmanı"]},
    "MAT1110": {"ad": "Analiz II", "sinif": 1, "yariyil": 2, "kategori": "Analiz", "tur": "ZORUNLU", "icerik": "Bu ders; belirli ve belirsiz integral kavramlarını, Riemann integralini, Kalkülüsün Temel Teoremini ve gelişmiş integrasyon tekniklerini kapsar. İntegral yardımıyla alan, hacim ve yay uzunluğu hesaplarının yanı sıra dizi ve serileri, kuvvet serilerini, Taylor ve Maclaurin açılımlarını detaylıca inceler.", "meslekler": ["Sinyal ve Görüntü İşleme Mühendisi", "Aktüer ve Risk Analisti", "Sayısal Metotlar Uzmanı"]},
    "MAT1108": {"ad": "Analitik Geometri II", "sinif": 1, "yariyil": 2, "kategori": "Geometri", "tur": "ZORUNLU", "icerik": "Bu ders; 3 boyutlu uzayda ikinci dereceden kuadrik yüzeyleri (küre, silindir, koni, elipsoid, hiperboloid ve paraboloid) ve bu yüzeylerin düzlem kesitlerini detaylıca inceler. Dönel yüzeyler, teğet düzlemler, dik doğrular ve uzaysal koordinat dönüşümlerinin cebirsel ve geometrik analizini kapsar.", "meslekler": ["CAD/CAM Yazılım Mühendisi", "Oyun Motoru Fizik & Çarpışma Mühendisi", "Medikal Görüntüleme ve 3B Rekonstrüksiyon Uzmanı"]},
    "IST2225": {"ad": "İstatistik I", "sinif": 2, "yariyil": 1, "kategori": "İstatistik", "tur": "ZORUNLU", "icerik": "Bu ders; veri özetleme tekniklerini, olasılık uzaylarını, rastgele değişkenleri ve temel olasılık dağılımlarını (Binom, Poisson, Normal vb.) kapsar. Beklenen değer, varyans, moment üreten fonksiyonlar ile olasılık kuramının omurgasını oluşturan Büyük Sayılar Yasası ve Merkezi Limit Teoremi'ni matematiksel aksiyomlarla ele alır.", "meslekler": ["Veri Bilimci ve Veri Analisti", "Kredi ve Risk Analisti", "Biyoistatistik Uzmanı"]},
    "MAT2205": {"ad": "Topoloji I", "sinif": 2, "yariyil": 1, "kategori": "Topoloji", "tur": "ZORUNLU", "icerik": "Bu ders; topolojik uzay kavramını, açık ve kapalı kümeleri, taban ve alt taban yapılarını, komşulukları ve ayırma aksiyomlarını kapsar. Topolojik uzaylarda süreklilik, homeomorfizma, tıkızlık (compactness) ve bağlantılılık (connectedness) gibi şekillerin esnetilip büküldüğünde korunan soyut geometrik niteliklerini matematiksel aksiyomlarla ele alır.", "meslekler": ["Topolojik Veri Analisti (TDA)", "Manifold Öğrenme Uzmanı (Yapay Zeka)", "Ağ Mimarisi Uzmanı"]},
    "MAT2253": {"ad": "Bilgisayar Programlama I", "sinif": 2, "yariyil": 1, "kategori": "Yazılım", "tur": "ZORUNLU", "icerik": "Bu ders; algoritmik düşünme yapısını, temel veri tiplerini, akış kontrol mekanizmalarını (döngüler, koşullu ifadeler), fonksiyon tanımlamayı ve diziler/matrisler üzerinde veri işlemeyi kapsar. Matematiksel problemleri ve sayısal yöntemleri (kök bulma, matris operasyonları, seriler) bilgisayar ortamında koda dönüştürme ve algoritma karmaşıklığını anlama süreçlerini uygulamalı olarak ele alır.", "meslekler": ["Yazılım Geliştirme Mühendisi", "Veri Mühendisi", "Hesaplamalı Matematik Uzmanı"]},
    "MAT2255": {"ad": "Analiz III", "sinif": 2, "yariyil": 1, "kategori": "Analiz", "tur": "ZORUNLU", "icerik": "Bu ders; tek değişkenli analizden n uzayındaki çok değişkenli fonksiyonlara geçişi, kısmi türevleri, yönlü türevleri, gradyan vektörünü ve Jakobiyen matrislerini kapsar. Çok değişkenli fonksiyonlarda kısıtlı ve kısıtsız ekstremum problemlerini Lagrange çarpanları yöntemiyle çözmeyi, çift ve üçlü katlı integralleri ele alır.", "meslekler": ["Yapay Zeka ve Derin Öğrenme Mühendisi", "Ekonometri Uzmanı", "Otonom Araç Çevre Algılama Uzmanı"]},
    "IST2226": {"ad": "İstatistik II", "sinif": 2, "yariyil": 2, "kategori": "İstatistik", "tur": "ZORUNLU", "icerik": "Bu ders; nokta ve aralık tahmini yöntemlerini (Maksimum Olabilirlik - MLE, Momentler Yöntemi), güven aralıklarını ve hipotez testi kuramını (Tip I/II hatalar, p-değeri, Neyman-Pearson Lemması) kapsar. Ki-Kare testleri, uyum iyiliği testleri, varyans analizi (ANOVA) ve basit doğrusal regresyon ile örneklem verisinden kitle parametrelerine dair matematiksel çıkarım yapma tekniklerini işler.", "meslekler": ["A/B Test ve Büyüme Analisti", "İstatistiksel Modelleyici (ML)", "Risk ve Kredi Tahmin Analisti"]},
    "MAT2206": {"ad": "Topoloji II", "sinif": 2, "yariyil": 2, "kategori": "Topoloji", "tur": "ZORUNLU", "icerik": "Bu ders; çarpım uzaylarını, bölüm uzaylarını , ileri ayırma aksiyomlarını, Urysohn Lemması ve Tietze Genişletme Teoremi'ni kapsar. Metrikleşebilirlik teoremlerini, metrik uzaylarda tamlık kavramını, Tychonoff Teoremi ile tıkızlaştırma yöntemlerini ve temel grup (homotopi) kavramına girişi detaylıca ele alır.", "meslekler": ["Robotik Hareket Planlama Mühendisi", "Yüksek Boyutlu Veri Analisti", "Kuantum Bilişim Araştırmacısı"]},
    "MAT2254": {"ad": "Bilgisayar Programlama II", "sinif": 2, "yariyil": 2, "kategori": "Yazılım", "tur": "ZORUNLU", "icerik": "Bu ders; Nesne Yönelimli Programlama (OOP) ilkelerini (sınıflar, nesneler, kalıtım, kapsülleme), gelişmiş veri yapılarını, dosya yönetimini ve hata yakalama mekanizmalarını kapsar. Modüler yazılım geliştirme prensipleri ile bilimsel hesaplama kütüphanelerini kullanarak karmaşık matematiksel algoritmaları ve veri işleme süreçlerini nesne tabanlı yapıda tasarlama becerisini işler.", "meslekler": ["Backend / Yazılım Mimarisi Mühendisi", "Veri Analisti ve ML Geliştiricisi", "Oyun ve Simülasyon Yazılımcısı"]},
    "MAT2256": {"ad": "Analiz IV", "sinif": 2, "yariyil": 2, "kategori": "Analiz", "tur": "ZORUNLU", "icerik": "Bu ders; vektör alanlarını, eğrisel integralleri, yüzey integrallerini ve akı (flux) hesaplarını kapsar. Green, Stokes ve Gauss (Iraksama) teoremleri ile vektör kalkülüsünün temel korunum yasalarını derinlemesine işler.", "meslekler": ["Akışkanlar Mekaniği (CFD) Simülasyon Mühendisi", "Elektromanyetik Sistemler Mühendisi", "Geometrik Derin Öğrenme Uzmanı"]},
    "MAT3301": {"ad": "Cebir I", "sinif": 3, "yariyil": 1, "kategori": "Cebir", "tur": "ZORUNLU", "icerik": "Bu ders; grup kavramını, alt grupları, devirli (siklik) grupları, permütasyon ve simetri gruplarını, Lagrange Teoremi'ni, normal alt grupları ve bölüm gruplarını kapsar. Grup homomorfizmaları, izomorfizm teoremleri ve otomorfizmalar yardımıyla soyut matematiksel yapıların simetri özelliklerini aksiyomatik boyutta derinlemesine inceler.", "meslekler": ["Kriptoloji ve Siber Güvenlik Mimarı", "Blokzincir Protokol Mühendisi", "Kuantum Bilişim Analisti"]},
    "MAT3313": {"ad": "Nümerik Analiz I", "sinif": 3, "yariyil": 1, "kategori": "Uygulamalı Matematik", "tur": "ZORUNLU", "icerik": "Bu ders; hata analizini (yuvarlama ve kesme hataları), tek değişkenli doğrusal olmayan denklemlerin kök bulma yöntemlerini ve doğrusal denklem sistemlerinin sayısal çözümlerini kapsar. Polinomsal interpolasyon ile sayısal türev ve integral hesaplama tekniklerini matematiksel ve algoritmik yaklaşımlarla ele alır.", "meslekler": ["Hesaplamalı Mühendislik Yazılımcısı", "Quant Finansal Risk Analisti", "Veri Bilimci / Algoritma Optimizasyon Uzmanı"]},
    "MAT3315": {"ad": "Diferensiyel Denklemler I", "sinif": 3, "yariyil": 1, "kategori": "Diferansiyel Denklemler", "tur": "ZORUNLU", "icerik": "Bu ders; birinci basamaktan diferensiyel denklemleri (ayrılabilir, tam, lineer, Bernoulli/Riccati), yüksek basamaktan sabit katsayılı lineer denklemleri, belirsiz katsayılar ve parametrelerin değişimi yöntemleri ile Laplace dönüşümlerini kapsar.", "meslekler": ["Kontrol ve Otonom Sistemler Mühendisi", "Algoritmik Ticaret Analisti", "Fiziksel Simülasyon Yazılımcısı"]},
    "MAT3317": {"ad": "Kompleks Fonksiyonlar Teorisi I", "sinif": 3, "yariyil": 1, "kategori": "Analiz", "tur": "ZORUNLU", "icerik": "Bu ders; karmaşık sayılar kümesini, karmaşık düzlemdeki topolojiyi, Cauchy-Riemann denklemlerini ve analitik (holomorf) fonksiyon kavramını kapsar. Karmaşık düzlemde eğrisel integralleri, Cauchy İntegral Teoremi ve Formülü'nü derinlemesine ele alır.", "meslekler": ["Sinyal İşleme ve Haberleşme Mühendisi", "Akışkanlar Dinamiği Simülasyon Yazılımcısı", "Kuantum Sistemler Mühendisi"]},
    "MAT3319": {"ad": "Diferensiyel Geometri I", "sinif": 3, "yariyil": 1, "kategori": "Geometri", "tur": "ZORUNLU", "icerik": "Bu ders; 3-boyutlu Öklid uzayında uzay eğrilerinin geometrisini, teğet vektör alanlarını, parametreleştirmeyi ve yay uzunluğu (arc length) kavramını kapsar. Frenet-Serret çatılarını, eğrilik (curvature) ve burulma (torsion) kavramları ile Eğrilerin Temel Teoremi'ni derinlemesine ele alır.", "meslekler": ["Otonom Araç Yörünge Mühendisi", "3B CAD/VFX Yazılım Mühendisi", "Robotik Kinematik Uzmanı"]},
    "MAT3302": {"ad": "Cebir II", "sinif": 3, "yariyil": 2, "kategori": "Cebir", "tur": "ZORUNLU", "icerik": "Bu ders; halka (ring) yapısını, alt halkaları, idealleri, bölüm halkalarını, halka homomorfizmalarını, tamlık bölgelerini ve polinom halkalarını kapsar. Cisim genişlemelerini, asal ve maksimal idealleri ile sonlu cisimleri (Galois alanları) aksiyomatik ve yapısal boyutlarıyla ele alır.", "meslekler": ["Post-Kuantum Kriptoloji Mühendisi", "Sıfır Bilgi İspatı (ZK) Protokol Mühendisi", "Hata Düzeltme Kodları Uzmanı"]},
    "MAT3314": {"ad": "Nümerik Analiz II", "sinif": 3, "yariyil": 2, "kategori": "Uygulamalı Matematik", "tur": "ZORUNLU", "icerik": "Bu ders; matrislerin özdeğer ve özvektörlerinin sayısal hesaplanmasını, adi diferensiyel denklemlerin başlangıç ve sınır değer problemlerinin sayısal çözümlerini ve kısmi türevli denklemlere sayısal yaklaşım tekniklerini kapsar.", "meslekler": ["HPC / Hesaplamalı Bilim Uzmanı", "Yapay Zeka Çekirdek Algoritma Mühendisi", "Quant PDE Çözücü Analisti"]},
    "MAT3316": {"ad": "Diferensiyel Denklemler II", "sinif": 3, "yariyil": 2, "kategori": "Diferansiyel Denklemler", "tur": "ZORUNLU", "icerik": "Bu ders; lineer diferensiyel denklem sistemlerini, varlık ve teklik teoremlerini (Picard-Lindelöf), seri çözümlerini (Frobenius yöntemi) ve lineer olmayan sistemlerde kararlılık analizini kapsar.", "meslekler": ["Robotik Kontrol ve Sistem Mühendisi", "Hesaplamalı Biyoloji Analisti", "Sistemik Risk ve Finans Analisti"]},
    "MAT3318": {"ad": "Kompleks Fonksiyonlar Teorisi II", "sinif": 3, "yariyil": 2, "kategori": "Analiz", "tur": "ZORUNLU", "icerik": "Bu ders; konform (açı koruyan) dönüşümleri, Schwarz-Christoffel dönüşümünü, Riemann Kaplama Teoremi'ni, harmonik fonksiyonları ve Dirichlet problemini kapsar.", "meslekler": ["CFD ve Aerodinamik Simülasyon Yazılımcısı", "Elektromanyetik Potansiyel Alan Mühendisi", "Hesaplamalı Geometri Mühendisi"]},
    "MAT3320": {"ad": "Diferensiyel Geometri II", "sinif": 3, "yariyil": 2, "kategori": "Geometri", "tur": "ZORUNLU", "icerik": "Bu ders; 3-boyutlu Öklid uzayında yüzeyler teorisini, teğet düzlemleri, I. ve II. Temel Formları, Şekil Operatörünü (Weingarten dönüşümü) ile Gauss ve Ortalama Eğrilik kavramlarını kapsar.", "meslekler": ["3B Yüzey Modelleme Yazılımcısı", "Jeodezik Rota ve Seyir Uzmanı", "Hesaplamalı Mimari Tasarımcısı"]},
    "MAT4001": {"ad": "Bitirme Projesi", "sinif": 4, "yariyil": 1, "kategori": "Genel", "tur": "ZORUNLU", "icerik": "Bu ders; öğrencinin lisans eğitimi boyunca edindiği teorik matematiksel birikimi ve algoritmik düşünme becerilerini bağımsız bir araştırma, geliştirme veya uygulama projesinde sentezlemesini kapsar.", "meslekler": ["Ar-Ge ve Modelleme Uzmanı", "Akademisyen / Araştırma Görevlisi", "Teknik Proje Yöneticisi"]},

    # ---------------- SEÇMELİ DERSLER ----------------
    "MAT2229": {"ad": "Matematik Laboratuvarı I", "sinif": 2, "yariyil": 1, "kategori": "Yazılım", "tur": "SEÇMELİ", "icerik": "Bilgisayarlı cebir ve hesaplama sistemlerini (MATLAB, SageMath, Mathematica veya Python ekosistemi) kullanarak sembolik ve nümerik hesaplamaları, matris operasyonlarını, 2B/3B fonksiyon grafiklerinin çizimini ve kök bulma algoritmalarını kapsar.", "meslekler": ["Hesaplamalı Matematik Uzmanı", "Bilimsel Yazılım Geliştiricisi", "Veri ve Algoritma Analisti"]},
    "MAT2267": {"ad": "Matematik Tarihi", "sinif": 2, "yariyil": 1, "kategori": "Tarih", "tur": "SEÇMELİ", "icerik": "Antik Mısır, Babil ve Yunan matematiğinden İslam Dünyası'nın altın çağına ve modern analizin doğuşuna kadar sayı sistemlerinin, geometrinin, cebirin ve kalkülüsün evrimini kapsar.", "meslekler": ["Bilim İletişimcisi ve Yazarı", "Akademisyen / Bilim Historikeri", "Matematik Eğitimi ve Müfredat Uzmanı"]},
    "MAT2333": {"ad": "Tasarı Geometri", "sinif": 2, "yariyil": 1, "kategori": "Geometri", "tur": "SEÇMELİ", "icerik": "Üç boyutlu uzay nesnelerini iki boyutlu düzlem üzerinde teknik olarak ifade etmeyi sağlar. Dik ve eğik izdüşüm yöntemlerini, uzayda nokta, doğru ve düzlem elemanlarının izdüşümsel durumlarını kapsar.", "meslekler": ["CAD/CAM ve 3B Modelleme Yazılımcısı", "3B Rendering Uzmanı", "Hesaplamalı Tasarım Analisti"]},
    "MAT2230": {"ad": "Matematik Laboratuvarı II", "sinif": 2, "yariyil": 2, "kategori": "Yazılım", "tur": "SEÇMELİ", "icerik": "Bilgisayarlı matematik ve programlama dilleri kullanılarak diferansiyel denklem sistemlerinin sayısal çözümlerini, eğri uydurma analizlerini, optimizasyon problemlerini ve stokastik simülasyon tekniklerini kapsar.", "meslekler": ["Makine Öğrenmesi Mühendisi", "Hesaplamalı Simülasyon Uzmanı", "Algoritma Geliştirici"]},
    "MAT2270": {"ad": "Sayılar Teorisi", "sinif": 2, "yariyil": 2, "kategori": "Cebir", "tur": "SEÇMELİ", "icerik": "Bölünebilme kurallarını, asal sayıları, modüler aritmetiği, lineer kongrüansları, Çin Kalan Teoremi'ni, Fermat, Euler ve Wilson teoremleri ile ilkel kökleri kapsar.", "meslekler": ["Kriptografi ve Siber Güvenlik Uzmanı", "Blokzincir Geliştiricisi", "Algoritma ve Veri Güvenliği Analisti"]},
    "MAT2272": {"ad": "Kombinatorik", "sinif": 2, "yariyil": 2, "kategori": "Ayrık Matematik", "tur": "SEÇMELİ", "icerik": "Güvercin yuvası ilkesi, saymanın temel ilkeleri, permütasyon, kombinasyon, içerme-dışarma prensibi, üretici fonksiyonlar ve yineleme bağıntılarını kapsar.", "meslekler": ["Algoritma Mühendisi", "Veri Bilimcisi ve Olasılık Analisti", "Ağ ve Optimizasyon Uzmanı"]},
    "MAT2276": {"ad": "İngilizce Matematiksel Kavramlar", "sinif": 2, "yariyil": 2, "kategori": "İletişim", "tur": "SEÇMELİ", "icerik": "Temel analiz, cebir, geometri ve uygulamalı matematik kavramlarının İngilizce karşılıklarını, formal tanım kalıplarını, teorem ispatı ifade biçimlerini ve akademik makale okuma/yazma tekniklerini kapsar.", "meslekler": ["Uluslararası Ar-Ge Araştırmacısı", "Küresel Teknik Yazar ve Çevirmen", "Global Veri Analisti"]},
    "MAT3329": {"ad": "Matematik Laboratuvarı III", "sinif": 3, "yariyil": 1, "kategori": "Yazılım", "tur": "SEÇMELİ", "icerik": "Kısmi türevli denklemlerin (PDE) sayısal çözümlerini, optimizasyon algoritmalarını, görselleştirme araçlarını ve büyük veri setlerinin matematiksel analizini derinlemesine ele alarak ileri düzey teorik matematiği endüstriyel yazılımlara dönüştürür.", "meslekler": ["HPC ve Bilimsel Simülasyon Mühendisi", "Kıdemli Algoritma Mühendisi", "Yapay Zeka Çekirdek Uzmanı"]},
    "MAT3331": {"ad": "Kinematik", "sinif": 3, "yariyil": 1, "kategori": "Fizik", "tur": "SEÇMELİ", "icerik": "Vektörel kinematik, eğrisel hareketler, hız ve ivme bileşenleri, dönme hareketleri, Euler açıları ve mekanizmaların hareket denklemlerini kapsar.", "meslekler": ["Robotik Kinematik Mühendisi", "Fizik Simülasyonu Yazılımcısı", "Uçuş Yörünge Analisti"]},
    "MAT3335": {"ad": "Kriptoloji", "sinif": 3, "yariyil": 1, "kategori": "Uygulamalı Matematik", "tur": "SEÇMELİ", "icerik": "Klasik şifreleme yöntemlerini, simetrik şifreleme blok algoritmalarını, açık anahtarlı kriptografi sistemlerini ve anahtar değişim protokollerini kapsar.", "meslekler": ["Kriptolog ve Siber Güvenlik Uzmanı", "Blokzincir Güvenlik Mühendisi", "Veri Gizliliği Mimarı"]},
    "MAT3337": {"ad": "Fraktal Geometri", "sinif": 3, "yariyil": 1, "kategori": "Geometri", "tur": "SEÇMELİ", "icerik": "Hausdorff boyutu, kendi kendine benzerlik, yinelenen fonksiyon sistemleri ile Julia ve Mandelbrot kümeleri gibi non-lineer dinamik sistem kavramlarını kapsar.", "meslekler": ["Prosedürel Grafik Mühendisi", "Fraktal Anten Tasarımcısı", "Kaotik Sistemler Analisti"]},
    "MAT3339": {"ad": "Doğrusal Programlama", "sinif": 3, "yariyil": 1, "kategori": "Optimizasyon", "tur": "SEÇMELİ", "icerik": "Doğrusal programlama modellerini kurma, Simpleks yöntemi, ikilik (duality) teorisi, duyarlılık analizi ve taşıma/atama problemlerinin çözüm algoritmalarını kapsar.", "meslekler": ["Optimizasyon Uzmanı", "Tedarik Zinciri Analisti", "Kaynak Planlama Uzmanı"]},
    "MAT3321": {"ad": "Algoritmalar ve Veri Yapıları", "sinif": 3, "yariyil": 1, "kategori": "Yazılım", "tur": "SEÇMELİ", "icerik": "Doğrusal ve doğrusal olmayan veri yapılarını (diziler, bağlı listeler, ağaçlar ve graflar), arama/sıralama algoritmalarını ve bu algoritmaların Big-O notasyonu ile zaman/bellek karmaşıklığı analizini kapsar.", "meslekler": ["Yazılım ve Algoritma Geliştiricisi", "Backend Sistem Mimarisi Mühendisi", "AI Veri Yapıları Mühendisi"]},
    "MAT3345": {"ad": "Sembolik Programlama Dilleri", "sinif": 3, "yariyil": 1, "kategori": "Yazılım", "tur": "SEÇMELİ", "icerik": "Bilgisayarlı cebir sistemlerini, LISP veya Prolog benzeri sembolik/mantıksal programlama paradigmalarını, analitik türev ve integral işlemlerinin harfsel çözüm algoritmalarını kapsar.", "meslekler": ["Bilgisayarlı Cebir Yazılımcısı", "Uzman Sistemler Mühendisi", "Bilimsel Yazılım Otomasyon Uzmanı"]},
    "MAT3322": {"ad": "Makine Öğrenmesi İçin Matematik", "sinif": 3, "yariyil": 2, "kategori": "Yapay Zeka", "tur": "SEÇMELİ", "icerik": "Çok değişkenli diferansiyel hesap, lineer cebir ayrışımları (SVD, PCA), olasılık ve istatistiksel kestirim ile konveks optimizasyon konularını kapsar.", "meslekler": ["Makine Öğrenmesi Araştırmacısı", "Kıdemli Veri Bilimci", "Derin Öğrenme Mühendisi"]},
    "MAT3330": {"ad": "Matematik Laboratuvarı IV", "sinif": 3, "yariyil": 2, "kategori": "Yazılım", "tur": "SEÇMELİ", "icerik": "Kısmi türevli denklemlerin sonlu elemanlar (FEM) veya sonlu farklar (FDM) yöntemleriyle sayısal çözüm simülasyonlarını, paralel matris hesaplama kütüphanelerini kapsar.", "meslekler": ["HPC Mühendisi", "Bilimsel Simülasyon Yazılımcısı", "Performans Optimizasyon Uzmanı"]},
    "MAT3336": {"ad": "Optimizasyon", "sinif": 3, "yariyil": 2, "kategori": "Optimizasyon", "tur": "SEÇMELİ", "icerik": "Lineer olmayan optimizasyon, konveks küme ve fonksiyonlar, KKT koşulları, Lagrange çarpanları, gradyan iniş yöntemleri ve temel optimizasyon algoritmalarını kapsar.", "meslekler": ["Optimizasyon Mühendisi", "Yapay Zeka Optimizasyon Uzmanı", "Portföy Optimizasyon Analisti"]},
    "MAT3340": {"ad": "Spektral Teori", "sinif": 3, "yariyil": 2, "kategori": "Analiz", "tur": "SEÇMELİ", "icerik": "Normlu ve Hilbert uzaylarında lineer operatörlerin spektrumu, rezolvent kümesi, kompakt operatörler, izdüşüm operatörleri ile öz-eşlenik (self-adjoint) operatörlerin spektral teoremlerini kapsar.", "meslekler": ["Kuantum Bilişim Araştırmacısı", "Matematiksel Fizik Modelleme Uzmanı", "Spektral Veri Analitiği Mühendisi"]},
    "MAT3344": {"ad": "Dönüşümler ve Geometriler", "sinif": 3, "yariyil": 2, "kategori": "Geometri", "tur": "SEÇMELİ", "icerik": "İzometriler, benzerlikler, afin dönüşümler, projektif dönüşümler, çemberlere göre ters dönüşüm (inversiyon) ve dönüşüm gruplarının değişmezleri teorisini kapsar.", "meslekler": ["Bilgisayar Grafikleri Yazılımcısı", "Robotik Koordinat Dönüşümleri Uzmanı", "Uzaysal Modelleme Araştırmacısı"]},
    "MAT3348": {"ad": "İntegral Denklemler", "sinif": 3, "yariyil": 2, "kategori": "Diferansiyel Denklemler", "tur": "SEÇMELİ", "icerik": "Fredholm ve Volterra tipi lineer integral denklemlerini, çekirdek (kernel) fonksiyonlarını, ardışık yaklaşımlar metodunu ve tekil integral denklemlerini kapsar.", "meslekler": ["Matematiksel Fizik Araştırmacısı", "Sınır Elemanları Simülasyon Mühendisi", "İleri Analiz Algoritma Uzmanı"]},
    "MAT3362": {"ad": "Projektif Geometri", "sinif": 3, "yariyil": 2, "kategori": "Geometri", "tur": "SEÇMELİ", "icerik": "Homojen koordinatlar, projektif düzlem, Desargues ve Pappus teoremleri, çift oran, konikler ve projektif dönüşüm gruplarını kapsar.", "meslekler": ["Bilgisayar Görüşü Mühendisi", "3B Bilgisayar Grafikleri Geliştiricisi", "Cebirsel Geometri Araştırmacısı"]},
    "MAT3366": {"ad": "Kodlama Teorisi", "sinif": 3, "yariyil": 2, "kategori": "Uygulamalı Matematik", "tur": "SEÇMELİ", "icerik": "Sonlu cisimler, doğrusal kodlar, Hamming kodları, devirli kodlar ve Reed-Solomon hata düzeltme kodlama tekniklerini kapsar.", "meslekler": ["Kanal Kodlama Mühendisi", "Depolama Sistemleri Uzmanı", "Kod Tabanlı Kriptografi Araştırmacısı"]},
    "MAT3376": {"ad": "Özel Fonksiyonlar", "sinif": 3, "yariyil": 2, "kategori": "Diferansiyel Denklemler", "tur": "SEÇMELİ", "icerik": "Gama ve Beta fonksiyonları, Bessel fonksiyonları, Legendre polinomları, Hermite ve Laguerre polinomları ile Hipergeometrik fonksiyonların seri çözümlerini kapsar.", "meslekler": ["Matematiksel Fizik Araştırmacısı", "Simülasyon ve Analiz Mühendisi", "Bilimsel Hesaplama Geliştiricisi"]},
    "MAT3378": {"ad": "Fonksiyonel Analize Giriş", "sinif": 3, "yariyil": 2, "kategori": "Analiz", "tur": "SEÇMELİ", "icerik": "Metriklendirilmiş uzaylar, normlu uzaylar, Banach uzayları, Hilbert uzayları, sınırlı lineer operatörler ile Hahn-Banach ve Banach-Steinhaus gibi temel teoremleri kapsar.", "meslekler": ["Kuantum Bilişim Araştırmacısı", "Matematiksel Fizik Uzmanı", "Çekirdek Metotları Veri Uzmanı"]},
    "MAT4401": {"ad": "Fonksiyonel Analiz", "sinif": 4, "yariyil": 1, "kategori": "Analiz", "tur": "SEÇMELİ", "icerik": "Genelleştirilmiş fonksiyonlar (dağılımlar teorisi), zayıf yakınsama, spektral ayrışımlar, Hahn-Banach teoreminin ileri uygulamaları ve Banach cebirlerini kapsar.", "meslekler": ["Kuantum Bilişim Araştırmacısı", "Matematiksel Modelleme Uzmanı", "İleri Analiz Ar-Ge Mühendisi"]},
    "MAT4405": {"ad": "Matematiksel Yöntemler ve Uygulamaları", "sinif": 4, "yariyil": 1, "kategori": "Uygulamalı Matematik", "tur": "SEÇMELİ", "icerik": "Kompleks değişkenler teorisi, adi ve kısmi diferensiyel denklemlerin analitik çözümleri, sınır değer problemleri, perturbasyon (bozuntu) teorisi ve integral dönüşümleri konularını kapsar.", "meslekler": ["Matematiksel Modelleme Mühendisi", "Ar-Ge Hesaplamalı Analiz Uzmanı", "Bilimsel Simülasyon Geliştiricisi"]},
    "MAT4407": {"ad": "Reel Analiz", "sinif": 4, "yariyil": 1, "kategori": "Analiz", "tur": "SEÇMELİ", "icerik": "Lebesgue ölçülebilir kümeler, ölçülebilir fonksiyonlar, Lebesgue integrali, yakınsama teoremleri ile LP uzaylarını kapsar.", "meslekler": ["Kantitatif Finans Uzmanı", "Stokastik Modelleme Araştırmacısı", "İleri Analiz Ar-Ge Uzmanı"]},
    "MAT4409": {"ad": "Saçılım Teorisi", "sinif": 4, "yariyil": 1, "kategori": "Matematiksel Fizik", "tur": "SEÇMELİ", "icerik": "Schrödinger denklemi için saçılım amplitüdü, faz kayması, Lippmann-Schwinger denklemi, Born yaklaşımı ve ters saçılım problemlerini kapsar.", "meslekler": ["Kuantum Saçılım Araştırmacısı", "Radar ve Sinyal Yayılım Mühendisi", "Ters Çözüm Tomografi Uzmanı"]},
    "MAT4411": {"ad": "Diferensiyellenebilir Manifoldlar", "sinif": 4, "yariyil": 1, "kategori": "Geometri", "tur": "SEÇMELİ", "icerik": "Türevlenebilir manifoldlar, teğet uzaylar, vektör alanları, tensör alanları, diferensiyel formlar ve genel Stokes teoremini kapsar.", "meslekler": ["Geometrik Modelleme Araştırmacısı", "Uzay-Zaman Fizik Uzmanı", "Robotik Konfigürasyon Uzmanı"]},
    "MAT4413": {"ad": "Diferensiyel Denklem Sistemleri", "sinif": 4, "yariyil": 1, "kategori": "Diferansiyel Denklemler", "tur": "SEÇMELİ", "icerik": "Lineer diferensiyel denklem sistemleri, matris üstelleri, özdeğer ve özvektör yöntemleri, kararlılık analizi, faz portreleri ve non-lineer sistemlerin lineerleştirilmesi konularını kapsar.", "meslekler": ["Dinamik Sistemler Mühendisi", "Matematiksel Modelleme Uzmanı", "Otonom Sistemler Ar-Ge Mühendisi"]},
    "MAT4415": {"ad": "Kompleks Analiz", "sinif": 4, "yariyil": 1, "kategori": "Analiz", "tur": "SEÇMELİ", "icerik": "Kompleks sayılar, analitik fonksiyonlar, Cauchy-Riemann denklemleri, çember ve eğri integralleri, Cauchy integral teoremi, Taylor ve Laurent serileri ile Rezidü teoremini kapsar.", "meslekler": ["Kompleks Sistemler Uzmanı", "Simülasyon Mühendisi", "Kantitatif Finans Analisti"]},
    "MAT4417": {"ad": "İleri Topoloji", "sinif": 4, "yariyil": 1, "kategori": "Topoloji", "tur": "SEÇMELİ", "icerik": "Tychonoff teoremi, Urysohn Lemma, Tietze Genişleme Teoremi, kompaktlaştırma yöntemleri, temel grup ve homotopi teorisinin temellerini kapsar.", "meslekler": ["Topolojik Veri Analizi Uzmanı", "Cebirsel Topoloji Araştırmacısı", "Robotik Konfigürasyon Uzmanı"]},
    "MAT4421": {"ad": "Kısmi Türevli Denklemlere Giriş", "sinif": 4, "yariyil": 1, "kategori": "Diferansiyel Denklemler", "tur": "SEÇMELİ", "icerik": "Birinci ve ikinci mertebeden kısmi türevli denklemler, karakteristikler yöntemi, dalga denklemi, ısı denklemi, Laplace ve Poisson denklemleri ile değişkenlerine ayırma yöntemini kapsar.", "meslekler": ["Matematiksel Modelleme Mühendisi", "Akışkanlar Dinamiği (CFD) Uzmanı", "Bilimsel Hesaplama Uzmanı"]},
    "MAT4429": {"ad": "Matematik Laboratuvarı V", "sinif": 4, "yariyil": 1, "kategori": "Yazılım", "tur": "SEÇMELİ", "icerik": "İleri düzey matris hesaplamaları, diferensiyel denklemlerin nümerik çözümleri, optimizasyon algoritmaları, sembolik hesaplama ve matematiksel veri görselleştirme tekniklerini kapsar.", "meslekler": ["Bilimsel Yazılım Geliştiricisi", "Nümerik Analiz Uzmanı", "Optimizasyon Uzmanı"]},
    "MAT4433": {"ad": "İleri Programlama", "sinif": 4, "yariyil": 1, "kategori": "Yazılım", "tur": "SEÇMELİ", "icerik": "Nesne yönelimli programlama mimarileri, gelişmiş veri yapıları ve algoritmalar, bellek yönetimi, tasarım kalıpları ve büyük ölçekli matematiksel simülasyon kodlarının optimizasyonunu kapsar.", "meslekler": ["Kıdemli Yazılım Mühendisi", "Bilimsel Yazılım Geliştiricisi", "Sistem Mimarisi Uzmanı"]},
    "MAT4437": {"ad": "Harmonik Analiz", "sinif": 4, "yariyil": 1, "kategori": "Analiz", "tur": "SEÇMELİ", "icerik": "Fourier serileri, Fourier dönüşümleri, Plancherel teoremi, dağılımlar teorisi, konvolüsyon operatörleri ve dalgacık analizinin temellerini kapsar.", "meslekler": ["Sinyal İşleme Mühendisi", "Görüntü Analitiği Uzmanı", "Dalga Yayılımı Araştırmacısı"]},
    "MAT4441": {"ad": "Kesirli Diferensiyel Denklemler", "sinif": 4, "yariyil": 1, "kategori": "Diferansiyel Denklemler", "tur": "SEÇMELİ", "icerik": "Riemann-Liouville ve Caputo türev tanımları, kesirli mertebeden adi ve kısmi diferensiyel denklemler, bellek etkileri, anomal difüzyon modelleri ile analitik ve nümerik çözüm yöntemlerini kapsar.", "meslekler": ["Anomal Difüzyon Uzmanı", "Viskoelastik Malzeme Mühendisi", "Biyomedikal Modelleme Uzmanı"]},
    "MAT4443": {"ad": "Fark Denklemleri", "sinif": 4, "yariyil": 1, "kategori": "Dinamik Sistemler", "tur": "SEÇMELİ", "icerik": "Lineer ve non-lineer fark denklemleri, denge noktaları, kararlılık analizi, Z-dönüşümü, üreteç fonksiyonları ve finans/ekonomi ile biyolojideki uygulamalarını kapsar.", "meslekler": ["Zaman Serileri Analisti", "Kantitatif Risk Uzmanı", "Algoritmik Ticaret Mühendisi"]},
    "MAT4447": {"ad": "Öklid Dışı Geometriler", "sinif": 4, "yariyil": 1, "kategori": "Geometri", "tur": "SEÇMELİ", "icerik": "Hiperbolik geometri, eliptik geometri, Poincaré disk ve yarı düzlem modelleri, eğrilik kavramları ve bu uzaylardaki trigonometrik bağıntıları kapsar.", "meslekler": ["Kozmoloji Araştırmacısı", "3D Grafik Mühendisi", "Konumsal Modelleme Uzmanı"]},
    "MAT4451": {"ad": "Ortogonal Polinomlar", "sinif": 4, "yariyil": 1, "kategori": "Uygulamalı Matematik", "tur": "SEÇMELİ", "icerik": "Legendre, Chebyshev, Hermite, Laguerre ve Jacobi polinomları, üç terimli nüks bağıntıları, Rodrigues formülleri, Sturm-Liouville teorisi ile nümerik entegrasyon uygulamalarını kapsar.", "meslekler": ["Nümerik Analiz Uzmanı", "Algoritma Geliştiricisi", "Sinyal İşleme Mühendisi"]},
    "MAT4461": {"ad": "Gruplar Teorisi", "sinif": 4, "yariyil": 1, "kategori": "Cebir", "tur": "SEÇMELİ", "icerik": "Gruplar, altgruplar, devirli gruplar, Lagrange teoremi, normal altgruplar, bölüm grupları, grup homomorfizmleri, permütasyon grupları, Cayley teoremi ve Sylow teoremlerini kapsar.", "meslekler": ["Kriptografi Uzmanı", "Post-Kuantum Güvenlik Araştırmacısı", "Cebirsel Kodlama Uzmanı"]},
    "MAT4463": {"ad": "Tensör Cebiri", "sinif": 4, "yariyil": 1, "kategori": "Cebir", "tur": "SEÇMELİ", "icerik": "Vektör uzaylarının direkt çarpımı, tensör çarpımı, kovaryant ve kontravaryant tensörler, indeks notasyonu, dönüşüm kanunları, simetrik ve antisimetrik tensörler ile dış çarpım konularını kapsar.", "meslekler": ["Sürekli Ortam Analisti", "Bilgisayarlı Görü Uzmanı", "Uzay-Zaman Araştırmacısı"]},
    "MAT4487": {"ad": "Matematiksel Modelleme", "sinif": 4, "yariyil": 1, "kategori": "Uygulamalı Matematik", "tur": "SEÇMELİ", "icerik": "Model kurma aşamaları, boyut analizi, analitik ve sayısal çözüm yaklaşımları, model doğrulama ve duyarlılık analizi konularını kapsar.", "meslekler": ["Simülasyon Mühendisi", "Süreç Optimizasyon Uzmanı", "Kantitatif Analist"]},
    "MAT4489": {"ad": "Operatör Teoriye Giriş", "sinif": 4, "yariyil": 1, "kategori": "Analiz", "tur": "SEÇMELİ", "icerik": "Banach ve Hilbert uzayları üzerinde sınırlı ve sınırsız operatörler, spektral teori, rezidü kümesi, spektrum çeşitleri, kompakt operatörler, izdihom operatörleri ve öz-eşlenik operatörleri kapsar.", "meslekler": ["Kuantum Bilişim Uzmanı", "Spektral Analiz Uzmanı", "Nümerik Algoritma Mühendisi"]},
    "MAT4497": {"ad": "Kategori", "sinif": 4, "yariyil": 1, "kategori": "Soyut Matematik", "tur": "SEÇMELİ", "icerik": "Nesneler, morfizmler (oklar), funktorlar, doğal dönüşümler, limitler ve kolimitler ile eş-adıllık kavramlarını kapsar.", "meslekler": ["Tip Teorisi Mimarı", "Kategorik Veri Modeli Uzmanı", "Soyut Matematik Araştırmacısı"]},
    "MAT4499": {"ad": "Ayrık Matematikte Özel Konular", "sinif": 4, "yariyil": 1, "kategori": "Ayrık Matematik", "tur": "SEÇMELİ", "icerik": "Ramsey teorisi, matroit teorisi, ileri sayma teknikleri, sonlu cisimler üzerindeki kombinatorik yapılar, ağ akışları ve algoritma karmaşıklığı konularını kapsar.", "meslekler": ["Algoritma Mühendisi", "Ağ Topolojisi Analisti", "Kriptografi Uzmanı"]},
    "AST321": {"ad": "Astronomi Tarihi", "sinif": 4, "yariyil": 1, "kategori": "Astronomi", "tur": "SEÇMELİ", "icerik": "Mezopotamya, Mısır, Antik Yunan, İslam astronomi altın çağı, Kopernik devrimi, Kepler yasaları, Galileo'nun teleskopik gözlemleri ve modern astrofiziğe geçiş süreçlerini kapsar.", "meslekler": ["Bilim Tarihçisi", "Bilim İletişimcisi", "Arkeoastronomi Araştırmacısı"]},
    "AST213": {"ad": "Astronomi I", "sinif": 4, "yariyil": 1, "kategori": "Astronomi", "tur": "SEÇMELİ", "icerik": "Gök küresi, koordinat sistemleri, zaman sistemleri, yerin hareketleri, ışık kırılması ve paralaks, Kepler yasaları ile gök mekaniğinin temellerini kapsar.", "meslekler": ["Uydu Yörünge Uzmanı", "Astrofizik Araştırmacısı", "Astronomi Veri Bilimcisi"]},
    "BİY415": {"ad": "İklim Bilgisi", "sinif": 4, "yariyil": 1, "kategori": "Biyoloji/Çevre", "tur": "SEÇMELİ", "icerik": "Atmosferin bileşimi ve katmanları, sıcaklık, basınç ve rüzgar sistemleri, nem ve yağış rejimleri, iklim sınıflandırma sistemleri, paleoklimatoloji ile güncel küresel iklim değişikliği dinamiklerini kapsar.", "meslekler": ["İklim Değişikliği Uzmanı", "Meteorolojik Veri Analisti", "Çevresel Risk Uzmanı"]},
    "BİY417": {"ad": "Çevre Kirliliği", "sinif": 4, "yariyil": 1, "kategori": "Biyoloji/Çevre", "tur": "SEÇMELİ", "icerik": "Kirletici bozunum kinetiği, adveksiyon-difüzyon denklemleri, endüstriyel ve evsel atık dinamikleri, ekotoksikoloji ile çevresel risk analizi ve azaltım stratejilerini kapsar.", "meslekler": ["Çevre Modelleme Uzmanı", "ÇED ve Risk Analisti", "Atık Yönetimi Mühendisi"]},
    "MAT4402": {"ad": "Fark Denklem Sistemleri", "sinif": 4, "yariyil": 2, "kategori": "Dinamik Sistemler", "tur": "SEÇMELİ", "icerik": "Lineer fark denklem sistemleri, matris formülasyonları, özdeğer ve özvektör analizleri, denge durumları, kararlılık kriterleri, non-lineer sistemlerin doğrusallaştırılması ve çoklu değişkenli zaman serisi modellerini kapsar.", "meslekler": ["Kantitatif Finans Analisti", "Dinamik Sistemler Uzmanı", "Makroekonomik Projeksiyon Uzmanı"]},
    "MAT4404": {"ad": "Cisim Genişlemeleri", "sinif": 4, "yariyil": 2, "kategori": "Cebir", "tur": "SEÇMELİ", "icerik": "Basit genişlemeler, cebirsel ve aşkın elemanlar, derecesi sonlu genişlemeler, parçalanma cisimleri, cebirsel kapanış ve Galois teorisinin temellerini oluşturan otomorfizma gruplarını kapsar.", "meslekler": ["Kriptografi Uzmanı", "Cebirsel Kodlama Uzmanı", "Sayılar Teorisi Araştırmacısı"]},
    "MAT4406": {"ad": "Uygulamalı Matematik", "sinif": 4, "yariyil": 2, "kategori": "Uygulamalı Matematik", "tur": "SEÇMELİ", "icerik": "Perturbasyon (tedirgisme) teorisi, asimptotik analiz, varyasyonlar hesabı, integral denklemler ve matematiksel fizik problemlerinin çözüm yöntemlerini kapsar.", "meslekler": ["Ar-Ge Mühendisi", "Simülasyon Uzmanı", "Operasyonel Araştırma Uzmanı"]},
    "MAT4408": {"ad": "Fourier Analizi", "sinif": 4, "yariyil": 2, "kategori": "Analiz", "tur": "SEÇMELİ", "icerik": "Fourier serileri, trigonometrik yaklaşım, yakınsama teoremleri, Fourier dönüşümü, ters dönüşüm, konvolüsyon teoremi, Parseval özdeşliği ve ısı/dalga denklemlerinin sınır değer problemlerine uygulanmasını kapsar.", "meslekler": ["Sinyal İşleme Mühendisi", "Akustik Analisti", "Zaman Serileri Analisti"]},
    "MAT4412": {"ad": "Geometriler ve Topoloji", "sinif": 4, "yariyil": 2, "kategori": "Geometri", "tur": "SEÇMELİ", "icerik": "Öklid dışı geometriler, metrik uzaylar, topolojik uzaylar, kompaktlık, bağlantılılık, temel grup ve yüzeylerin sınıflandırılması konularını kapsar.", "meslekler": ["Topolojik Veri Uzmanı", "3D Geometri Mühendisi", "Geometrik Kozmoloji Araştırmacısı"]},
    "MAT4414": {"ad": "Dinamik Sistemler", "sinif": 4, "yariyil": 2, "kategori": "Dinamik Sistemler", "tur": "SEÇMELİ", "icerik": "Faz uzayı, akışlar, denge noktalarının kararlılık analizi, çatallanma teorisi, limit çevrimleri ve kaos teorisinin temellerini kapsar.", "meslekler": ["Simülasyon Mühendisi", "Piyasa Dinamikleri Analisti", "Kompleks Sistemler Araştırmacısı"]},
    "MAT4430": {"ad": "Matematik Laboratuvarı VI", "sinif": 4, "yariyil": 2, "kategori": "Yazılım", "tur": "SEÇMELİ", "icerik": "Diferensiyel denklemlerin ve denklem sistemlerinin sayısal çözümleri, büyük boyutlu matris hesaplama algoritmaları, optimizasyon rutinleri, gelişmiş grafik görselleştirme teknikleri ve bilimsel hesaplama kütüphanelerinin uygulamalarını kapsar.", "meslekler": ["Bilimsel Hesaplama Mühendisi", "Veri Bilimi Yazılım Uzmanı", "Nümerik Algoritma Geliştirici"]},
    "MAT4432": {"ad": "Uygulamalı Kısmi Türevli Denklemler", "sinif": 4, "yariyil": 2, "kategori": "Diferansiyel Denklemler", "tur": "SEÇMELİ", "icerik": "Birinci ve ikinci mertebeden KTD'ler, karakteristikler yöntemi, dalga denklemi, ısı denklemi, Laplace denklemi, değişkenlerine ayırma metodu, Fourier serileri ve Green fonksiyonları konularını kapsar.", "meslekler": ["Simülasyon Mühendisi", "Kantitatif Finans Analisti", "CFD Uzmanı"]},
    "MAT4436": {"ad": "Modüller Teorisi", "sinif": 4, "yariyil": 2, "kategori": "Cebir", "tur": "SEÇMELİ", "icerik": "Modül kavramı, altmodüller, bölüm modülleri, modül homomorfizmleri, serbest modüller, projeksiyon ve enjektif modüller, temel ideal bölgeleri üzerindeki sonlu üretilmiş modüllerin yapısı ve tensör çarpımları konularını kapsar.", "meslekler": ["Soyut Cebir Araştırmacısı", "Kriptografi Uzmanı", "Akademik Ar-Ge Uzmanı"]},
    "MAT4440": {"ad": "Yarı Riemann Geometrisi", "sinif": 4, "yariyil": 2, "kategori": "Geometri", "tur": "SEÇMELİ", "icerik": "Yarı Riemann manifoldları (Lorentzian manifoldları), Levi-Civita bağlantısı, eğrilik tensörleri, jeodezik eğriler ve Einstein alan denklemlerinin geometrik altyapısını kapsar.", "meslekler": ["Uzay-Zaman Araştırmacısı", "Gravitasyonel Fizik Uzmanı", "İleri Geometri Uzmanı"]},
    "MAT4442": {"ad": "Lie Grupları", "sinif": 4, "yariyil": 2, "kategori": "Cebir", "tur": "SEÇMELİ", "icerik": "Düzgün manifoldlar ile grup yapısının birleştiği Lie gruplarını, Lie cebirlerini, birim elemandaki teğet uzayları, üstel dönüşümü, matris Lie gruplarını ve temel temsil teorisini kapsar.", "meslekler": ["Kuantum Bilişim Uzmanı", "Robotik Kinematik Mühendisi", "Geometri Araştırmacısı"]},
    "MAT4448": {"ad": "Kesirli Fark Denklemleri", "sinif": 4, "yariyil": 2, "kategori": "Dinamik Sistemler", "tur": "SEÇMELİ", "icerik": "Nabla ve Delta kesirli fark operatörleri, kesirli toplam ve fark formülasyonları, kesirli mertebeli fark denklemlerinin analitik ve sayısal çözüm yöntemleri, Mittag-Leffler tipi kesikli fonksiyonlar ile bu sistemlerin kararlılık analizini kapsar.", "meslekler": ["Matematiksel Modelleme Uzmanı", "Kantitatif Risk Analisti", "Dinamik Sistemler Araştırmacısı"]},
    "MAT4452": {"ad": "Topolojik Vektör Uzaylarına Giriş", "sinif": 4, "yariyil": 2, "kategori": "Analiz", "tur": "SEÇMELİ", "icerik": "Lokal konveks uzaylar, yarı norm aileleri, Hahn-Banach teoreminin analitik ve geometrik versiyonları, lineer dönüşümlerin sürekliliği, Fréchet uzayları ve Banach uzaylarının temellerini kapsar.", "meslekler": ["Fonksiyonel Analiz Araştırmacısı", "Kuantum Sistemleri Uzmanı", "İleri Analiz Uzmanı"]},
    "MAT4472": {"ad": "Uygulamalı Kompleks Analiz", "sinif": 4, "yariyil": 2, "kategori": "Analiz", "tur": "SEÇMELİ", "icerik": "Kompleks türev ve integral, Cauchy-Riemann denklemleri, harmonik fonksiyonlar, Cauchy integral teoremi, rezidü teoremi ve kontür integralleri, konformal tasvirler ile Laplace denkleminin sınır değer problemlerine uygulanmasını kapsar.", "meslekler": ["Akışkanlar Modelleme Mühendisi", "Anten Tasarım Uzmanı", "Kantitatif Finans Analisti"]},
    "MAT4490": {"ad": "Halkalar Teorisi", "sinif": 4, "yariyil": 2, "kategori": "Cebir", "tur": "SEÇMELİ", "icerik": "Halka kavramı, altrakalar, idealler, bölüm halkaları, halka homomorfizmleri, asal ve maksimal idealler, polinom halkaları, tamlık bölgeleri, esas ideal bölgeleri ve Noetherci halkalar konularını kapsar.", "meslekler": ["Kriptografi Uzmanı", "Cebirsel Kodlama Uzmanı", "Cebir Araştırmacısı"]},
    "BLM446": {"ad": "Bulanık Mantık", "sinif": 4, "yariyil": 2, "kategori": "Yapay Zeka", "tur": "SEÇMELİ", "icerik": "Kesin kümeler ve bulanık kümeler arasındaki farklar, üyelik fonksiyonları, bulanık küme işlemleri, dilsel değişkenler, bulanık kural tabanlı sistemler, Mamdani ve Sugeno çıkarım mekanizmaları ile bulanık kontrol süreçlerini kapsar.", "meslekler": ["Yapay Zeka Mühendisi", "Otomasyon Uzmanı", "Karar Destek Uzmanı"]}
}

# ==============================================================================
# ARAYÜZ TASARIMI
# ==============================================================================
st.title("🎓 Matematik Bölümü Kariyer ve Yapay Zekâ Rehberi")
st.write("Derslerin teorik içeriklerini inceleyebilir veya doğrudan Yapay Zekâ asistanına danışarak kariyer rotanı çizebilirsin.")

# 3 Sekme oluşturuyoruz: Listeleme, Sorgulama ve AI Asistan
tab1, tab2, tab3 = st.tabs(["📚 Müfredat Listesi", "🔍 Detaylı Ders Sorgula", "🤖 Yapay Zekâ Kariyer Asistanı"])

with tab1:
    filtre = st.radio("Listelenecek Ders Türü:", ["TÜMÜ", "ZORUNLU", "SEÇMELİ"], horizontal=True)
    st.divider()
    for sinif in [1, 2, 3, 4]:
        sinif_dersleri = {k: v for k, v in dersler_db.items() if v["sinif"] == sinif and (filtre == "TÜMÜ" or v["tur"] == filtre)}
        if sinif_dersleri:
            st.subheader(f"📌 {sinif}. Sınıf Dersleri")
            sirali_dersler = sorted(sinif_dersleri.items(), key=lambda x: (x[1]['yariyil'], x[1]['tur'], x[0]))
            for kod, d in sirali_dersler:
                etiket = "🔴 ZORUNLU" if d["tur"] == "ZORUNLU" else "🟢 SEÇMELİ"
                donem_adi = "Güz" if d["yariyil"] == 1 else "Bahar"
                with st.expander(f"**{kod}** - {d['ad']} | {etiket}"):
                    st.caption(f"**Kategori:** {d['kategori']} | **Dönem:** {d['sinif']}. Sınıf / {d['yariyil']}. Yarıyıl ({donem_adi})")
                    st.markdown(f"**📖 İçerik:** {d['icerik']}")
                    st.write("**🎯 Kariyer Yolları:**")
                    for meslek in d['meslekler']:
                        st.markdown(f"- *{meslek}*")

with tab2:
    st.subheader("Özel Ders Arama")
    ders_listesi = ["Bir ders seçin..."] + sorted(list(dersler_db.keys()))
    secilen_kod = st.selectbox("Ders Kodu Seçin:", ders_listesi)
    if secilen_kod != "Bir ders seçin...":
        d = dersler_db[secilen_kod]
        donem_adi = "Güz" if d["yariyil"] == 1 else "Bahar"
        st.success(f"**{secilen_kod} - {d['ad']}**")
        col1, col2 = st.columns(2)
        with col1:
            st.info(f"**Statü:** {d['tur']}")
            st.info(f"**Dönem:** {d['sinif']}. Sınıf / {d['yariyil']}. Yarıyıl ({donem_adi})")
        with col2:
            st.info(f"**Kategori:** {d['kategori']}")
        st.write("---")
        st.write(f"**İçerik Detayı:**\n{d['icerik']}")
        st.write("---")
        st.write("**Bu Dersin Hazırladığı Meslekler:**")
        for m in d['meslekler']:
            st.markdown(f"- **{m}**")

# ==============================================================================
# YAPAY ZEKA ASİSTANI (GÜVENLİ VE GÜNCEL MODEL)
# ==============================================================================
with tab3:
    st.subheader("🤖 Yapay Zekâ Öğrenci Danışmanı")
    st.markdown("""
    Bu asistan; arka planda **Google Gemini AI** dil modelini kullanarak matematik bölümü müfredatını analiz eder. 
    Kariyer hedefinizi yazın, size hangi dersleri almanız gerektiğini anlatsın!
    """)
    
    st.divider()

    # Şifreyi açıkça yazmıyoruz, Streamlit'in gizli kasasından çekiyoruz!
    try:
        api_key = st.secrets["GEMINI_API_KEY"]
    except Exception:
        st.error("Sistem Hatası: API Anahtarı sunucuda bulunamadı! Lütfen Streamlit ayarlarından Secrets kısmını kontrol edin.")
        api_key = None

    if "messages" not in st.session_state:
        st.session_state.messages = []

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    if prompt := st.chat_input("Örn: Yapay zeka mühendisi olmak istiyorum, 3. sınıfta hangi seçmeli dersleri almalıyım?"):
        
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        if api_key:
            try:
                genai.configure(api_key=api_key)
                
                # Google'ın açıkça istediği en güncel modeli yazıyoruz:
                model = genai.GenerativeModel('gemini-3.6-flash')
                
                sistem_istemi = f"""
                Sen bir üniversitenin Matematik Bölümü öğrencileri için tasarlanmış profesyonel bir Akademik Yapay Zeka Danışmanısın.
                Sadece aşağıda sana verdiğim ders veri tabanını kullanarak öğrencilere kariyer ve ders seçimi tavsiyeleri ver.
                Veri tabanı dışında ders uydurma. Yanıtların kibar, teşvik edici ve net olsun.
                
                Müfredat Veri Tabanı:
                {dersler_db}
                
                Öğrencinin Sorusu: {prompt}
                """
                
                with st.chat_message("assistant"):
                    with st.spinner("Müfredat analiz ediliyor..."):
                        response = model.generate_content(sistem_istemi)
                        st.markdown(response.text)
                
                st.session_state.messages.append({"role": "assistant", "content": response.text})
                
            except Exception as e:
                with st.chat_message("assistant"):
                    st.error(f"Bağlantı hatası oluştu: {e}")
